# Generated by Django 5.0.6 on 2024-08-20 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyebbill',
            name='name',
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('location', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meter',
            },
        ),
        migrations.AddField(
            model_name='monthlyebbill',
            name='meter',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.meter'),
            preserve_default=False,
        ),
    ]
