# Generated by Django 5.0.6 on 2024-08-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_monthlyebbill_name_meter_monthlyebbill_meter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cons_no',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='meter',
            name='building_type',
            field=models.CharField(choices=[('DOMESTIC', 'DOMESTIC'), ('AGRICULTURE', 'AGRICULTURE'), ('COMMERCIAL', 'COMMERCIAL'), ('INDUSTRIAL', 'INDUSTRIAL')], default='Domestic', max_length=120),
            preserve_default=False,
        ),
    ]
