# Generated by Django 5.0.6 on 2024-08-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_customuser_cons_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='cons_no',
            field=models.CharField(default=0, max_length=25),
        ),
    ]
