# Generated by Django 5.0.6 on 2024-08-27 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_meter_cons_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monthlyebbill',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.meter'),
        ),
    ]
