# Generated by Django 5.0.6 on 2024-08-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_meter_user_alter_monthlyebbill_meter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='cons_no',
            field=models.CharField(default=0, max_length=25, unique=True),
        ),
    ]
